# Generated by Django 3.1.1 on 2021-06-13 11:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0005_auto_20210612_2224'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.ImageField(upload_to='')),
                ('sdate', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='customers.cart')),
            ],
        ),
    ]
