# Generated by Django 3.0.7 on 2021-06-05 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('customers_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('customers_fname', models.CharField(max_length=50)),
                ('customers_lname', models.CharField(max_length=10)),
                ('customers_address', models.CharField(max_length=10)),
                ('customers_phone_no', models.IntegerField(default=0)),
                ('customers_email', models.EmailField(max_length=200)),
                ('customers_dob', models.DateField()),
                ('cphoto_main', models.ImageField(upload_to='photos/%Y/%m/%d')),
                ('customers_city', models.CharField(max_length=50)),
                ('customers_state', models.CharField(max_length=50)),
                ('customers_password', models.CharField(max_length=50)),
            ],
        ),
    ]
