# Generated by Django 3.1.1 on 2021-06-12 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20210612_1412'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customers',
            old_name='cphoto_main',
            new_name='custmer_photo',
        ),
        migrations.RenameField(
            model_name='customers',
            old_name='customers_address',
            new_name='customer_address',
        ),
        migrations.RenameField(
            model_name='customers',
            old_name='customers_city',
            new_name='customer_city',
        ),
        migrations.RenameField(
            model_name='customers',
            old_name='customers_dob',
            new_name='customer_dob',
        ),
        migrations.RenameField(
            model_name='customers',
            old_name='customers_email',
            new_name='customer_email',
        ),
        migrations.RenameField(
            model_name='customers',
            old_name='customers_fname',
            new_name='customer_fname',
        ),
        migrations.RenameField(
            model_name='customers',
            old_name='customers_id',
            new_name='customer_id',
        ),
        migrations.RenameField(
            model_name='customers',
            old_name='customers_lname',
            new_name='customer_lname',
        ),
        migrations.RenameField(
            model_name='customers',
            old_name='customers_password',
            new_name='customer_password',
        ),
        migrations.RenameField(
            model_name='customers',
            old_name='customers_phone_no',
            new_name='customer_phone_no',
        ),
        migrations.RenameField(
            model_name='customers',
            old_name='customers_state',
            new_name='customer_state',
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_qty', models.IntegerField()),
                ('Customers_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='customers.customers')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='products.products')),
            ],
        ),
    ]
