# Generated by Django 3.1.1 on 2021-06-12 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_auto_20210612_2214'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='Customers_id',
            new_name='customers_id',
        ),
    ]
