# Generated by Django 3.1.1 on 2021-06-13 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_auto_20210612_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_pincode',
            field=models.ImageField(default=250110, upload_to=''),
            preserve_default=False,
        ),
    ]
