# Generated by Django 3.0.7 on 2021-06-03 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('product_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=50)),
                ('product_type', models.CharField(max_length=10)),
                ('product_volume', models.CharField(max_length=10)),
                ('product_qty', models.IntegerField(default=0)),
            ],
        ),
    ]
