# Generated by Django 3.0.7 on 2021-06-05 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210603_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
