# Generated by Django 3.0.7 on 2021-06-05 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_products_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_description',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
