# Generated by Django 3.1.1 on 2021-06-12 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_products_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_image',
            field=models.ImageField(upload_to='prowebsite/static/img/product/'),
        ),
    ]
